### ISSUE TITLE
Updateable Edge does not allow selecting a specific edge

### ISSUE THREAD

**Issue by TippyLion28** [xyflow/xyflow#1095]
https://pasteboard.co/JXiHNHg.jpg

As seen above, reactflow doesn't seem to care which edge the cursor is placed over, and therefore does not allow updating those edges.

**Comment by moklick** [comment]
good catch, thanks. I will try to find a solution for this.

**Comment by moklick** [comment]
Hey @TippyLion28. Can you check v9.5.5?

**Comment by TippyLion28** [comment]
Hi @moklick,

Saw a notification pop up in my email for this. Can confirm the issue is still present in 9.6.0

**Comment by datoslabs** [comment]
I have opened an issue - #1303, which seems to stem from the same root cause.  Inspecting the DOM, at the ends of each edge contains an invisible SVG `<Circle class="react-flow__edgeupdater">` which listens to the mouse events; when 2 edges shares a common `Handle`, the `edgeupdaters` overlap and only the topmost element can be selected.  

One possible solution is to allow users to move the edge anchor, ie the `Handle`, along the `Node's` edge to reveal the `edgeupdater` underneath for selection; to do so, the `Node` would dynamically create a unique `Handle` for each connected edge and position the `Handle` based on `event.clientX` / `event.clientY` and project the final position onto the `Node's` edge.

**Comment by pbenard73** [comment]
In waiting for a more convenient solution, I did a workaround in using css and `selectableElement`.

```css
  g.react-flow__edge:not(.selected) circle {
    pointer-events:none;
  }
```

**Comment by mohit-chauhan-stackpro** [comment]
> In waiting for a more convenient solution, I did a workaround in using css and `selectableElement`.
> 
> ```css
>   g.react-flow__edge:not(.selected) circle {
>     pointer-events:none;
>   }
> ```

Temporary solution. It will be more better to restrict edge dragging.

**Comment by moklick** [comment]
we will continue with the discussion in #3840
