### ISSUE TITLE
Does this support printing of the diagram?

### ISSUE THREAD

**Issue by PhilAndrew** [xyflow/xyflow#1104]
How about how to print the diagram or export to PDF or image file?

**Comment by moklick** [comment]
Hey, this is not supported. We are mixing DOM nodes with SVG so it's not a trivial task.

**Comment by moklick** [comment]
No, I haven't checked this in a while. I will re-open the issue and check the current status.

**Comment by moklick** [comment]
Generating an image of a flow is possible with a library like [html-to-image](https://github.com/bubkoo/html-to-image) as seen in this example https://reactflow.dev/examples/misc/download-image . We will not add something like this to the library.

**Comment by am001512** [comment]
Hi, Im trying to develop features printing and download image on nextjs. The download image on nextjs is not working because NextJS not accepting the ReactDOM (document.querySelector). I've trying to  inject it to the state in useEffect but the diagrams in blank.. Is there any another way to provide this ? Thanks
