### ISSUE TITLE
Shift Selection disappears when attempting to select outside of pane

### ISSUE THREAD

**Issue by xplato** [xyflow/xyflow#1654]
If you hold Shift + Click & Drag and try to select something at the far edge of the screen (past it, essentially), you'll see that the selection area disappears.

You can use this example from my previous issue:

- https://7bpqd.csb.app/; or
- https://codesandbox.io/s/hardcore-hodgkin-7bpqd?file=/src/App.js

Would it be possible to make it so that trying to select something past the edge of the ReactFlow area would scroll/overflow into the next area? Essentially, panning the view in the direction opposite that which the selection area overflows into.

**Comment by moklick** [comment]
Hey @flexplatox 

I like that idea but I guess it's not easy to implement. Right now it's the expected behaviour but I understand that it would be a better experience if you could automatically pan while selecting. 

We have other more important tasks but I will keep this open until we decide if it's doable.

**Comment by flexplatox** [comment]
I understand. Thank you for your response.

**Comment by agvawd** [comment]
I would really like to see this feature.  I have had several users ask for this. Could this be something that gets added in the near future?
