### ISSUE TITLE
`onNodesChange` gets triggered (incorrectly?) after programmatically `setNodes`

### ISSUE THREAD

**Issue by neo** [xyflow/xyflow#2405]
### Describe the Bug

I personally think that in a "controlled" setup, setting nodes from within the code shouldn't trigger `onNodesChange`; just like how in a react controlled form field, setting the value state won't trigger an `onChange` event, and only typing (equivalent to dragging and moving a node in our context) would trigger the change event.

### Your Example Website or App

https://codesandbox.io/s/sandpack-project-forked-dmfqkw?file=/App.js:1915-1953

### Steps to Reproduce the Bug or Issue

Drag a new node and drop it into the canvas would trigger `onNodesChange` and see a log in console.

### Expected behavior

It shouldn't trigger `onNodesChange` after programmatically setting nodes.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 104.0.5112.79

**Comment by moklick** [comment]
Hey @neo,

in the moment when you add a new node to the pane, it gets measured and the dimensions then get passed back to the user via `onNodesChange`. It's necessary to do this. Otherwise you do proper layouting for example.

**Comment by neo** [comment]
Hey Moritz!

Thank you for your response! While I kind of understand why it's necessary to emit new dimension, I still think it may be breaking the "controlled with state" paradigm that `onNodesChange` should only be triggered by "direct user change". I wonder if there's another way to send the dimension update 🤔

**Comment by moklick** [comment]
I understand that this is a bit confusing, but I don't have a better idea. I would not like to introduce another callback that would be needed to sync the node dimensions.

**Comment by bluesock** [comment]
would it be an idea to have a source property on the NodeChanges - set to "internal" for a programmatic change and maybe "user" for an interaction from the interface  - then the resulting array from onNodesChange could be filtered as required, in this case, to provide just  "direct user changes". I appreciate that's likely a lot of work but just a thought.

**Comment by tiagobento** [comment]
I'm having a similar problem... I'm using a controlled flow, and when I change my model externally, `onNodesChange` is getting called, notifying me about something I already know was done... after all, the nodes changed because I changed the model, so calling `onNodesChange` doesn't do anything for me... In fact, behaving this way only creates a duplicate change to my model, as I need to observe `onNodesChange` to trigger chances to my model for user interactions like selections and dragging.

Having a mechanism to "opt-out" of `onNodesChanged` when the changes are not triggered by user interaction would be very nice :) Also, I think it better aligns with the controlled flow of other components, like mentioned by @neo.

#### Example:
Imagine I render my diagram then click on a button called "Double node sizes". This button will trigger a change to my model, causing the nodes array to be "recalculated" and the `nodes` property of my Reactflow instance to be updated, with the new nodes and their doubled sizes. `onNodesChange` is getting called in this situation, but it's not necessary...

**Comment by neo** [comment]
I agree, that based on my observation, there might be a need to separate out the "active/user initiated" node change and the "passive/system" node change – so that we could potentially react on them separately

**Comment by tiagobento** [comment]
I was able to work around this issue by:
1. Making my mutations idempotent, so changing the dimensions/position etc of nodes will not trigger state updates if the values are identical to what I already had in my model. This was mainly achieved by preserving references and only updating terminal properties. I'm using Zustand + Immer, like ReactFlow so rightfully encourages. Was not hard at all :)
2. Implementing a debounce mechanism to handle state changes coming from ReactFlow (I'm using 500ms). This was also necessary to make some operations atomic, like deleting a bunch of nodes/edges with a single press keypress. Since `onEdgesChange` and `onNodesChange` are two separate callbacks.

Didn't have time to check the `xyflow` branch yet, but I'm hoping that there are updates to the state management for controlled flows 🙏

**Comment by moklick** [comment]
I thought about this again, and I still don't have a better idea. We support uncontrolled flows without the need of using `onNodesChange`/ `onEdgesChange` and controlled flows, where you are in charge of the nodes/edges state. If we would mix the two ways, it would get very messy, because there would be multiple sources of truth. In my view there is also no need of separating user and internal actions, because you can already distinguish them (position, remove and select is always user driven, the other ones are internal).
