### ISSUE TITLE
Text selection in textbox is canceled

### ISSUE THREAD

**Issue by ysds** [xyflow/xyflow#2837]
### Describe the Bug

When I try to select text in a textbox (input/textarea/contentEditable, etc...) in a node with the mouse, the selection is canceled when the cursor moves outside the node.

This behavior is not user-friendly for nodes whose primary function is text input, such as sticky note. Is there any way to prevent this?

### Your Example Website or App

https://reactflow.dev/docs/guides/custom-nodes/

### Steps to Reproduce the Bug or Issue

1. Go to the https://reactflow.dev/docs/guides/custom-nodes/
2. ~Add a "nodrag" class to the input.~ Not needed in the latest example
3. Input text to the right demo input.
4. Select the text with the mouse, hold the mouse down and move the mouse cursor out of the node.
5. Text selection is canceled.

### Expected behavior

The text selection state continues even if you go out of the node.

### Screenshots or Videos

https://user-images.githubusercontent.com/4065765/218458477-fc058d34-5d5a-43d5-be3c-99005750ee58.mov

### Platform

- OS: macOS
- Browser: Chrome

**Comment by chrtze** [comment]
I think it has something to do with `pointer-events: none` applied on `.react-flow__nodes`. If you set it to `pointer-events: all` it doesn't clear the selection. Not sure though how we can fix this.

**Comment by sskanishk** [comment]
@ysds It is due to javascript, if you observe video closely, cursor change itself from "text select" to "pan select/hand icon"(on the node but not on the input area) and then finally "link select" when it completely outside of the node i.e. cursor on canvas.

This is behaving same in windows machine, I don't think it an usability issue. 

JS enable cursor to "pan select" at non text input are of node so user can move the node.
"link select" is on canvas might be there is some clickable link is there.

**Comment by peterkogo** [comment]
This is due to the way text selection works in browsers in combination with transformed elements. Please refer to [this solution if it's bother you.](https://github.com/xyflow/xyflow/issues/4156#issuecomment-2056582433).
