### ISSUE TITLE
Null reference on unmounting and re-mounting NodesSelection component

### ISSUE THREAD

**Issue by ealjkl** [xyflow/xyflow#3488]
### Describe the Bug

Sometimes unmounting and mounting the NodesSelection component will not add the drag event listener to `react-flow__nodesselection-rect`.

### Your Example Website or App

https://codesandbox.io/s/jovial-sun-g6vsd5

### Steps to Reproduce the Bug or Issue

I'll give the steps to reproduce given the code in  https://codesandbox.io/s/jovial-sun-g6vsd5

1. Select the nodes with range selection
2. Click cut
2. Click paste
3. Try to drag the node

### Expected behavior

It should drag the nodes

### Platform

- OS: [Wsl2  1.2.5.0, Windows 11]
- Browser: [Edge, Brave, Chrome]
- Reactflow version : [11.9.2]

### Additional context

I entered the source code to understand the bug, and these are my insights: 

When NodesSelection component unmounts. And gets remounted, for some reason the nodeRef is null. It does eventually update to be the rectangle, but it is too late, the nodeRef has gone through the useDrag hook. And since changing nodeRef.current doesn't trigger updates, it stays without its event listener. 

A possible solution, altough ugly could be to imperatively check if there is a `react-flow__nodesselection-rect` element in the DOM, and imperatively set the ref current. 

It is really odd, to me, since the ref should be set before running the useEffects

**Comment by moklick** [comment]
The codesandbox uses a very old version of React Flow and React. Could you update that?

**Comment by moklick** [comment]
What are you trying to achieve? Why do you need `setState({ nodesSelectionActive: true})` ? This is only meant to be used internally.

**Comment by moklick** [comment]
please re-open with an answer to my question if the issue persists.

**Comment by smoothkitten** [comment]
@moklick This issue persist with the latest version. I encountered it and have been trying to understand for hours. The issue is as described by the other user. When a set of nodes cut/pasted or copy/pasted while they were selected by a "selection rect" there will be a new selection rect created for the pasted nodes however that newly created selection rect is not interactable (dragable). Version     "@xyflow/react": "^12.9.2" still has the same issue, I encountered while using this version.

How to get the bug:

- First have couple nodes on your screen.
- Multi select them by holding shift button on your keyboard, there will a dragable rectangle appear.
- Cut and paste the selected elements.
- After pasting rectangle will appear but won't be dragable anymore.

**Comment by smoothkitten** [comment]
user can get the rect back by creating it again after destryoing via setting nodesSelectionActive to false: 
```

        store.setState({
          userSelectionRect: {
            x: minX,
            y: minY,
            width: maxX - minX,
            height: maxY - minY,
            drawX: maxX,
            drawY: maxY,
          },
          nodesSelectionActive: true,
        });
```
