### ISSUE TITLE
onEdgesChange params does not include information about the trigger

### ISSUE THREAD

**Issue by RiccardoRomagnoli** [xyflow/xyflow#3501]
### Describe the Bug

When I delete an edge directly onEdgesChange gets called.
When I delete a node with an edge attacehd, onEdgesChange gets called.

Now, I have in place a "user confirmation" logic that happens depending certain conditions on deletion. 

The issue is that I do not know if onEdgesChange has been triggered because of a node deletion or a direct deletion and depending on that I need to perform a confirmation or not. 

onEdgesChange should also pass the information of the trigger, otherwise a controller flow is not aware of the actual state.

Any ideas?

### Steps to Reproduce the Bug or Issue

delete a edge
delete a node connected to another node

you do not know what deleted the edge

### Expected behavior

you know what deleted the edge

### Platform

- OS: any
- Browser: any
- Version: any

**Comment by baibhavbista** [comment]
Since React Flow does not have a `onBeforeDelete` callback ([yet](https://github.com/xyflow/xyflow/issues/3092#issuecomment-1568146728)), the way I ended up solving this is by disabling React Flow's deleteKeyCode, adding custom key handler and then handling the logic there. 

See https://github.com/xyflow/xyflow/discussions/2925#discussioncomment-6976130 by @AdamGerthel and https://github.com/xyflow/xyflow/discussions/2925#discussioncomment-7907136

cc @RiccardoRomagnoli  in case you still need a solution

**Comment by RiccardoRomagnoli** [comment]
Thanks for your comment. I ended up adding a `await delay(10)` in onEdgesChange which allows onNodesChange to be executed beforehand. Then, by setting a store variable I can know if the delete has been triggered by a node delete (confirmed by user) or edge delete (instant).

**Comment by moklick** [comment]
v12 has a `onBeforeDelete` handler. You can already try out the beta. Details: #3764

**Comment by moklick** [comment]
We added an `onBeforeDelete` in React Flow 12, that can be used for this.

If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12

**Comment by RiccardoRomagnoli** [comment]
Great work guys, keep it up!
