### ISSUE TITLE
E2E: Panel Plugin

### ISSUE THREAD

**Issue by peterkogo** [xyflow/xyflow#3607]
- [ ] Add a new test case in `examples/react/src/generic-tests` &  `examples/svelte/src/generic-tests`
- [ ] Create new E2E tests in `tests/playwright` for checking the functionality of the Panel Component

**Comment by Ankuristic** [comment]
Could You assign this task for End to End End Testing for Minimap component to me.

**Comment by moklick** [comment]
Hey @Ankuristic thanks again for offering your help. However if you write the same message to a lot of issues this looks like spam. If you want to help, you could comment here and ask how you could do that, but we won't just assign a task to you.

**Comment by Ankuristic** [comment]
we can start writing the test code like this:

test.describe('Panel', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/tests/generic/nodes/general');
  });  i not get any where the code of the Panel component and Minimap component . so can you help me where the code of component like minimap and panel so that i start write E2E test code code for that.
