### ISSUE TITLE
Scrolling does not work when zoomOnScroll=false

### ISSUE THREAD

**Issue by stanislav-grin** [xyflow/xyflow#3708]
### Describe the Bug

I'm facing an issue when trying to scroll a page, if the mouse position is over ReactFlow, the scroll does not work. ReactFlow has the zoomOnScroll={ false } property.

### Steps to Reproduce the Bug or Issue

1. Create react-flow component
2. Put it in the scrollable container
3. Set `zoomOnScroll` property to `false`
4. Try to scroll the page over react-flow component
5. Scrolling does not work

### Expected behavior

Scrolling should work when zoomOnScroll={ false }

### Platform

- OS: macOS
- Browser: Chrome
- Version: 119.0.6045.159

**Comment by bcakmakoglu** [comment]
This is not a bug but the expected behavior.

To allow for scrolling, you need to use the [`preventScrolling`](https://reactflow.dev/api-reference/react-flow#prevent-scrolling) prop and set it to `false`, that way you can scroll the container again without ReactFlow catching the events and blocking the page scroll.

**Comment by stanislav-grin** [comment]
Thanks a lot, @bcakmakoglu! Didn't notice this property.
