### ISSUE TITLE
Expose dx & dy in NodePositionChange in ReactFlow

### ISSUE THREAD

**Issue by tristanls** [xyflow/xyflow#4045]
### Please describe the feature that you want to propose

**Feature**: expose `dx` & `dy` (change in `x` position coordinate & change in `y` position coordinate) in `NodePositionChange` event in ReactFlow. _EDIT: for this use case, interested in `positionAbsolute.dx` & `positionAbsolute.dy` specifically_

**Motivation**: When xyflow is used with multiplayer technology, when moving a node, sending movement intent (i.e. changes, like dx & dy) is recommended over sending final positions. This allows for dealing with cases where two people attempt to move the same node.

While in some straightforward cases it is possible to reverse engineer dx & dy. In others (for example, when using scale factors that are separate from xyflow zoom level) it becomes problematic as scale factor multiplication starts to significantly distort dx & dy reconstruction beyond certain scales.

Even without scales, I am doing calculations to reconstruct dx & dy, where I'd rather not since xyflow already must have done it in order to generate NodePositionChange.

**Comment by moklick** [comment]
Thanks for the idea! We will check, if it's possible to send the delta along with the other changes.

**Comment by peterkogo** [comment]
@tristanls Thanks for your patience — we have been quite preoccupied with getting v12 out the door and fixing up loose ends.

Currently, you can easily determine deltas by calculating differences between the current position or size of the [InternalNode](https://reactflow.dev/api-reference/types/react-flow-instance#get-internal-node) and the `NodePositionChange` or `NodeDimensionChange`. [Here a small sandbox](https://codesandbox.io/p/sandbox/f67lf6) showing the rough idea.

Adding deltas on library side would add unwarranted complexity, due to the way we internally track and modify these changes.

Your concerns around scaling (I assume you mean adding some `transform: scale` to nodes) are justified, as RF does not support it. Internally, we do not correct for any additional transforms. It probably still works because we use [measured node dimensions](https://reactflow.dev/api-reference/types/internal-node#measured) to make any calculations. But note that this breaks apart the moment you add some kind of scaling to the node with an origin besides `[0, 0]`. I recommend leaving positioning and sizing in the hands of React Flow.

I will close this for now. Don't hesitate to continue the discussion or reopen the issue if any problems persist.

**Comment by tristanls** [comment]
Hi @peterkogo.

I will give reconstructing `dx` & `dy` using `InternalNode` a try. As long as this gives me back the user's input and remains available, it should be sufficient.

I'm confused by the sandbox example as I don't see it using `getInternalNode()` in the code.

**Comment by peterkogo** [comment]
@tristanls ah dang, codesandbox didn't save my changes. Will update it in a second.

**Comment by peterkogo** [comment]
Sorry having some issue with codesandbox. [Try this link here](https://codesandbox.io/p/sandbox/elastic-snowflake-lvz8h9?file=%2FApp.js%3A1%2C1-79%2C1).

**Comment by tristanls** [comment]
@peterkogo, the sandbox at the latest link is a good summary, I appreciate it.
