### ISSUE TITLE
[v12] More flexibility on Node and Edge types for data

### ISSUE THREAD

**Issue by sroussey** [xyflow/xyflow#4058]
### Please describe the feature that you want to propose

I have a separate graph that I then want to display. I thought it would be easiest to have the data field in xyflow's node or edge be a reference to the node or edge in my graph. So I tried setting the types like `Node<MyNodeClass>` and `Edge<MyEdgeClass>` but that gets lots of errors as you assume that MyNodeClass and MyEdgeClass is a derivative of `Record<string, any>`

**Comment by peterkogo** [comment]
We have updated a lot of things in v12 throughout the library in regards to typing functions & hooks. You can check out [the preliminary version of the guide](https://github.com/xyflow/web/blob/v12/sites/reactflow.dev/src/pages/learn/advanced-use/typescript.mdx) we wrote on how typing works with your custom nodes & edges.

In your specific case, because we have added better handling, updating and access of `node.data`, we had to make it a requirement that data is an object. In your case you could add the reference as `node.data.ref`.

Feel free to reopen the issue if this does not help.
