### ISSUE TITLE
defaultNodeOptions

### ISSUE THREAD

**Issue by akre54** [xyflow/xyflow#4066]
### Please describe the feature that you want to propose

[`defaultEdgeOptions`](https://reactflow.dev/api-reference/types/default-edge-options) is a great feature for extending all edges from a common set of properties. Would it be possible to do the same for `defaultNodeOptions`? Specifically I want all of my nodes to share a `dragHandle` className. Currently I'm just mapping over the array and setting the property in the return but it would be cleaner to do this the same way I can for edges. Thanks!

**Comment by peterkogo** [comment]
We are trying to be a little cautions about adding new props to the main component, because there are already quite a number of them.
Because edges are automatically created in an uncontrolled flow, there needs to be a way to configure them. The same is not true for nodes: if you want to add nodes you have to add them programmatically anyway, where you can spread some default properties.

**Comment by akre54** [comment]
Alrighty. Understandable, thanks. I do wish this prop were able to be passed to some default options though (even if not `defaultNodes`). I'll close but hope you'll revisit. Thanks
