### ISSUE TITLE
The edge path doesn't work well with the CSS scale.

### ISSUE THREAD

**Issue by 42arch** [xyflow/xyflow#4266]
### Describe the Bug

I'm trying to add the CSS style property `transform: scale(0.7)` to the reactflow component, but the edge path is shifted.
<img width="234" alt="1" src="https://github.com/xyflow/xyflow/assets/20656708/654e72f4-0dbe-45d9-ba19-0c0a4d3480f6">
<img width="284" alt="2" src="https://github.com/xyflow/xyflow/assets/20656708/b7a65303-1ba2-4ebf-8540-7093e51c3da2">

I don't know where the reason comes from. Maybe it's a react issue or an SVG issue? 
Thanks!

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-q272d9?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

Just like what's in the repro demo.

### Expected behavior

You can click the button on the demo page, if scaling it after a while, it goes well, without shifting.

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [124.0.6367.63]

**Comment by moklick** [comment]
Why do you want to scale the container? If you want to adjust the viewport, you should use `setViewport`.

**Comment by peterkogo** [comment]
React Flow needs the dimensions of the flow to figure out things - supporting scaling by transforms would add an immens overhead to this, because it would have to be respected in many internal calculations. You can however resize the flow component and adjust the zoom level of the viewport at the same time to achieve the same effect. (napkin math: halving the size while halving the zoom level should yield the same same effect as scaling)

**Comment by 42arch** [comment]
Thank you for your suggestion! I will try it out later.
