### ISSUE TITLE
accept array of classes in noPanClassName

### ISSUE THREAD

**Issue by fredericrous** [xyflow/xyflow#4294]
**Context**

Sometimes we do not have control over the library we use inside a node and cannot add the nopan class everywhere.
The workaround is to fork the library and add the nopan ourselves but this increases maintenance burden & cost

**Ask**

Could noPanClassName on ReactFlow component accept an array of selectors or an array of classes instead of just a string?

**Comment by peterkogo** [comment]
Can you elaborate a little more on you case? How it is not possible to add the noPan class to certain elements?

**Comment by fredericrous** [comment]
The elements are inside a library I do not own

**Comment by bcakmakoglu** [comment]
I'm not quite sure if this wouldn't introduced *new* problems though.

Let's say I use some library for a table and I want to set `nopan` on a table-cell that uses the class name `cell`.
Now I pass an array of class names to `noPanClassName` 

```tsx
<ReactFlow noPanClassName={['nopan', 'cell']} ...>
```

What would happen is that *every element* (nodes and edges) would receive two class names now since all elements receive the `noPanClassName` as well

```tsx
// wrapNode.tsx - this is an internal ReactFlow component wrapper for nodes

// ... some code

return (
  <div
    className={cc([
      'react-flow__node',
      `react-flow__node-${type}`,
      {
        // this is overwritable by passing `nopan` as a class name
        [noPanClassName]: isDraggable, // <--- this would now end up being multiple class names
      },
      className,
      {
        selected,
        selectable: isSelectable,
        parent: isParent,
        dragging,
      },
    ])}
// more code
```

So your node suddenly would receive styles that are applied to the `cell` class name, which obviously isn't what you intended to do - the intention was that any element with the `cell` class name would also just be ignored by panning.

I don't know if a new prop should be introduced for this, if there's really enough use-cases to warrant that or not but I believe you should be able to do this yourself without the new to pass an array of class names.

```ts
// let's query the elements that should have the `nopan` class name and add it ourselves
useEffect(() => {
    // select all elements with the `cell` class name
    const cells = document.querySelectorAll('.cell');
    
    cells.forEach(cell => {
	  // add the `nopan` class name
      cell.classList.add('nopan');
    });
}, [])
```

**Comment by peterkogo** [comment]
I agree with @bcakmakoglu here. I think there are plenty of possibilities to achieve what you are trying to do. Adding the `nopan` class to the elements you "don't control" programmatically sounds like a cleaner solution.

**Comment by fredericrous** [comment]
indeed [bcakmakoglu](https://github.com/bcakmakoglu) has a good point regarding classes that could possibly be targeted when developer do not want them to be targeted. However, document.querySelectorAll doesn't seem like an optimal solution. It is not available at server side rendering
