### ISSUE TITLE
Background pattern id ends with undefined

### ISSUE THREAD

**Issue by NicolaLC** [xyflow/xyflow#4430]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: React Flow v11
- Browser and version: Chrome 126.0.6478.126
- OS and version: Ubuntu 24.04 LTS

### Live code example

https://codesandbox.io/p/sandbox/react-flow-starter-ts-r69228

### Describe the Bug

By default, if you don't manually set the `Background` `id` property, the resulting id of the child pattern is:

`pattern1-undefined`

The desired outcome should be just `pattern1` by filtering out the id if undefined.

### Steps to reproduce the bug or issue

1. Add the `<Background />` component to the graph
2. Inspect its pattern HTML element
3. The id will be pattern1-`undefined`

### Expected behavior

The resulting id should filter out the undefined id passed as a property.

### Screenshots or Videos

![image](https://github.com/xyflow/xyflow/assets/3704156/7e0b6344-1966-4cea-a95b-d36399ed22f8)

### Additional context
I'm not sure if this Is intentional or not, but as I need to access that id for some styling customizations, using undefined might be an issue as the id might change in the future.

**Comment by moklick** [comment]
This is fixed in React Flow 12! https://reactflow.dev/learn/troubleshooting/migrate-to-v12

**Comment by NicolaLC** [comment]
> This is fixed in React Flow 12! https://reactflow.dev/learn/troubleshooting/migrate-to-v12

Thanks @moklick, will check that!

**Comment by livwvil** [comment]
> This is fixed

Hi @moklick!
I faced a similar problem in my project. I'm dealing with several flows at the same time. Also I use a broken layout manager that sets the width and height of the hidden splitpane to zero and breaks the flow. That's why I faced this!
If one flow is broken, the other flow uses the broken background. It looks like using a globally unique identifier (by default) will help.

![bg-react-flow](https://github.com/user-attachments/assets/36a89444-4811-417f-be42-0c5098855885)
