### ISSUE TITLE
V12 Migration: Node type imported from @xyflow/react is missing positionAbsolute field

### ISSUE THREAD

**Issue by shev7** [xyflow/xyflow#4606]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.1.1
- Browser and version: 
- OS and version:

### Describe the Bug

Before V12 we were using positionAbsolute to work with parent nodes, and many other staff related to positioning.
Now after upgrade to V12 positionAbsolute is missing in Node type imported from '@xyflow/react', but documentation saying that it is here.

https://reactflow.dev/api-reference/types/node#position-absolute

Can this field be used or not? Where the problem: in docs or in type definitions?
And if this field is deprecated, what can we use instead?

### Steps to reproduce the bug or issue

-

### Expected behavior

-

**Comment by bcakmakoglu** [comment]
The documentation is wrong about this and needs to be updated.
Since v12 *user nodes* (which are of type `Node`) do not have a field called `positionAbsolute` anymore.
These fields are only stored in *internal nodes* (which are of type `InternalNode`) as `internalNode.internals.positionAbsolute`.

If you need access to the internals like `positionAbsolute` you can use [`getInternalNode`](https://reactflow.dev/api-reference/types/react-flow-instance#get-internal-node) and access the property like this

```ts
const { getInternalNode } = useReactFlow()

const internalNode = getInternalNode(nodeId)

const positionAbsolute = internalNode.internals.positionAbsolute
```

**Comment by moklick** [comment]
Thanks! We updated the docs.
