### ISSUE TITLE
Reactflow not able to differentiate between click and double click events for both nodes and edges

### ISSUE THREAD

**Issue by shubhamjajoo** [xyflow/xyflow#4668]
### What platform were you using when you found the bug?

- React Flow  
^11.7.0
- Browser and version: 
chrome
- OS and version:

### Live code example
[Sandbox](https://codesandbox.io/p/sandbox/crazy-cannon-2ny9n8?workspaceId=c7852b00-d654-4582-8605-f82f08961ae5)

### Describe the Bug

Visit sandbox URL, Double click the node. 
It's triggering **click event handler** but no double click handler.

### Steps to reproduce the bug or issue

1. Go to sandbox example
2. Double Click on any of the node.
3. It's not triggering double click handler. (Sometimes triggers, but click handler is getting triggered first)

### Expected behavior

As a user, I expect **doubleClickHandler** should trigger when I double click the any of the node.
 But click handler is getting triggered.

**Comment by peterkogo** [comment]
This is not how double click events are handled by the browser. Making these events mutually exclusive would mean every click would be delayed by the maximum allowed time frame for a double click, which would feel very sluggish.

The reason it does not trigger all the time is because you are moving your mouse ever so slightly in between clicks, which starts dragging a node. Try setting the [`nodeDragThreshold`](https://reactflow.dev/api-reference/react-flow#node-drag-threshold) to something higher, like 2 or 3.
