### ISSUE TITLE
Node width fails to resize due to hardcoded width in CSS

### ISSUE THREAD

**Issue by txase** [xyflow/xyflow#4738]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.2
- Browser and version: All
- OS and version: All

### Live code example

https://codesandbox.io/p/sandbox/headless-cdn-cpz86l

### Describe the Bug

When node contents are wider than 150px (e.g. a long string of text without whitespace, as in the example), the measuring fails because the node styling is hardcoded to 150px wide.

https://github.com/xyflow/xyflow/blob/97fdff59d40071aee0b3192f7b571c6bdd4d09fd/packages/system/src/styles/style.css#L77

If this rule is overridden (like below), widths end up calculated correctly. I think the width just needs to be deleted from this CSS style.

```css
.react-flow__node-input,
.react-flow__node-default,
.react-flow__node-output,
.react-flow__node-group {
    width: auto
}
```

### Steps to reproduce the bug or issue

1. Make a flow
2. Set one of the node labels to be a long string of text, e.g. "kjsdhkjsfdhflskdjhfsjlkdfhkjlsdhfdlkhflskdfhjksldhfjkdhsfkjshdfljkc"
3. See the node width remains 150px wide, which isn't enough for the text

### Expected behavior

As a user using a browser, I expect the node to resize its width to be large enough for all text.

### Screenshots or Videos

<img width="524" alt="image" src="https://github.com/user-attachments/assets/c38eda00-2507-484f-8570-95afec307ee1">

**Comment by moklick** [comment]
Hey! The built-in nodes have default styles. Part of that default style is a fixed width. I regret it a bit, that we added those built-in nodes to the library at all, because they are more like example nodes and not nodes that you use in your application. As you said, one way is to overwrite the css, but the better way is to use custom nodes when the default styles not match your use case.
