### ISSUE TITLE
ERROR: ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by bsvetlik** [xyflow/xyflow#4792]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: @xyflow-12.3.4
- Browser and version: Latest Chrome, Edge, FireFox
- OS and version: Windows 10

### Describe the Bug

When our browser application loads multiple flows simultaneously, we occasionally encounter a Webpack DevServer black screen with the error "ResizeObserver loop completed with undelivered notifications.".
This error seems to be specific to React Flow, as it's the only library in our application that utilizes the ResizeObserver API.
Despite the error, React Flow diagrams are displayed correctly. However, we're concerned that this error might potentially impact the performance or functionality of the diagrams.

### Steps to reproduce the bug or issue

Load multiple Flows simultaneously.

### Expected behavior

No errors appear.

### Screenshots or Videos

![error-ResizeObserver loop completed with undelivered notifications](https://github.com/user-attachments/assets/0cce4916-8958-4605-a1f9-0e0ecb40a1d8)

**Comment by peterkogo** [comment]
I think you can safely ignore the warnings. We add a ResizeObserver for each node and with hot reloading might trigger this warning.

But just to make sure are you accessing `node.measured` inside your node and maybe changing it's dimensions based on it?

**Comment by bsvetlik** [comment]
Good to know we can safely disregard this error!
A few observations:
1. The error seems to occur only after a full page refresh, not during hot reloads.
2. Our code doesn't utilize the `node.measured` property

**Comment by nullromo** [comment]
I can **safely** ignore the warnings, but I cannot **sanely** ignore them. It gets annoying having to close the error every time.

I hit this message when trying to resize a node component based on its children.

```ts
// custom node component
export const MyNode = (props: NodeProps<Node<MyNodeData>>) => {
    // get a reference to the whole diagram
    const flowDiagram = useReactFlow<AnyNode, AnyEdge>();

    // find all children nodes of this node
    const children = flowDiagram.getNodes().filter((node) => {
        return node.parentId === props.id;
    });

    // size the content based on how many children are in it
    return (
        <div style={{ height: `${children.length * 30}px` }}>
            { /* content here */ }
        </div>
    );
};
```

Removing the `height: ...` part of the style makes the error stop occurring. Using a static number like `height: '10px'` also causes no errors.

### Question
Is there a "correct" way to resize a component based on its children?

**Comment by nullromo** [comment]
The workaround mentioned [here](https://github.com/xyflow/xyflow/issues/3076#issuecomment-2587294188) works, but it doesn't really seem "correct."

```ts
<ReactFlow
    onEdgesChange={(changes) => {
        setTimeout(() => {
            onEdgesChange(changes);
        });
    }}
    onNodesChange={(changes) => {
        setTimeout(() => {
            onNodesChange(changes);
        });
    }}
/>
```

**Comment by krishan91-ctrl** [comment]
I ran into this same `ResizeObserver loop completed with undelivered notifications` warning while using React Flow too — it usually popped up when I was dynamically resizing nodes based on their children.

In my case, it happened because the layout updates triggered a re-render that the ResizeObserver caught mid-cycle. It didn’t break anything visually, but the console spam got pretty annoying during development.

What helped was deferring the layout update slightly — for example, wrapping dimension updates in setTimeout or requestAnimationFrame — similar to the workaround mentioned above. That stopped the resize loop warning entirely.

I ended up digging into it a bit more and wrote down the causes and a few clean fixes here, in case it helps anyone else: [ResizeObserver loop completed with undelivered notifications – Causes & Fixes](https://techiesgrow.com/resizeobserver-loop-completed-undelivered-notifications/)

> It’s safe to ignore, but if you’re resizing nodes dynamically or using auto-layout logic, a small async delay before measurement usually prevents the warning from appearing.
