### ISSUE TITLE
Ability to provide pathLength to edge

### ISSUE THREAD

**Issue by mhuggins** [xyflow/xyflow#4821]
### Please describe the feature that you want to propose

Hello,

I'm trying to animate newly added edges via custom CSS rules.  I'd like to leverage the `stroke-dasharray` CSS rule to make it appear as though the edge is being drawn from the source to the target.  The problem is that without specifying a [`pathLength`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/pathLength) property on the `path` element, there's not a definitive way to consistently perform this using CSS alone.

Would is be possible to add this as an option for edges without the need to create a custom Edge component that's nearly identical to the ones provided?  Alternatively, would it be possible for `BaseEdge` to support other `path` attributes as props such that it can be leveraged easily when implementing custom Edge components?

Thank you!

**Comment by peterkogo** [comment]
We should definitely add the ability to pass any props to the path that a `BaseEdge` rendered. We should also forward the ref of the path when we are at it.

We don't want to add `pathLengh` as an option for the `BuiltInNodes` because they are just really there to simplify the first steps of working with React Flow. We want to prevent adding complexity to the whole data model, for something that can be easily solved within custom edges.

**Comment by mhuggins** [comment]
Makes sense.  I'm happy to put together a PR for the props + ref aspect, if that helps!

**Comment by mhuggins** [comment]
This was fixed in the linked PR! 😄

**Comment by moklick** [comment]
Thanks! This is fixed in 12.3.6.
