### ISSUE TITLE
How to set dynamic height of nodes based on html renders inside div and set x,y position acording to that.

### ISSUE THREAD

**Issue by VijayRathod20** [xyflow/xyflow#4837]
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 
- Browser and version: 
- OS and version:

### Describe the Bug

![image](https://github.com/user-attachments/assets/415c7571-dd05-4dfd-9fa0-4d2b9f508a26)

### Steps to reproduce the bug or issue

Created custom node with more data render inside the node , the height is increased but placeholder node not set properly

### Expected behavior

![image](https://github.com/user-attachments/assets/c9c34ab4-477a-488b-a5c9-c42188c74a68)

**Comment by moklick** [comment]
Please provide a codesandbox for this.

It seems that the height is correct but the layout is not updated accordingly. You could trigger a re-layout whenever the height of a node changes for example by comparing prev and current values or use the dimension change of `onNodesChange`.

@peterkogo what do you think about an `useOnNodesMeasure` hook and/or a `onNodesMeasure` prop?

**Comment by peterkogo** [comment]
@VijayRathod20 The offset of the placeholder node is hardcoded to appear 150px below the added node. You have to change that. Otherwise as @moklick already mentioned, the proper solution would be to trigger some kind of layout function after adding nodes with undeterminable dimensions.

Also please delete the codesandbox, as you just shared our pro example code if I am not mistaken.

**Comment by VijayRathod20** [comment]
Yes I found the issue and fixed, is there any demo for layouting with dynamic node height.
